version: "2"
services:
  jsconsole:
    image: "node:8"
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - ./:/home/node/app
    ports:
      - "127.0.0.1:8081:80"
    command: "npm start"